import { open, nav, SP } from "./helpers.mjs";
const { b, p, errors } = await open();
await p.evaluate(async () => {
  const d = window.__rabit.useData.getState();
  const iso = (n) => {
    const x = new Date();
    x.setDate(x.getDate() + n);
    return x.toISOString().slice(0, 10);
  };
  await d.addEvent({ title: "Backwards", date: iso(0), start: "15:00", end: "14:00" });
  await d.addEvent({ title: "Overnight", date: iso(0), start: "23:30", end: "00:30" });
  await d.addEvent({ title: "Zero", date: iso(0), start: "12:00", end: "12:00" });
  await d.addEvent({ title: "", date: iso(0) });
  await d.addTask({ title: "   ", date: iso(0), time: "08:00" });
  await d.addRoutine({ title: "RBack", day: 0, start: "10:00", end: "09:00" });
  await d.addRoutine({ title: "RLate", day: 6, start: "23:00", end: "23:59" });
  await d.addNote({ title: "<img src=x onerror=alert(1)>", body: "<b>bold?</b>" });
});
await nav(p, "Calendar");
await p.getByText("WEEK", { exact: true }).first().click();
await p.waitForTimeout(900);
await p.screenshot({ path: `${SP}/qa4-week.png` });
await p.getByText("DAY", { exact: true }).first().click();
await p.waitForTimeout(900);
await p.screenshot({ path: `${SP}/qa4-day.png` });
await nav(p, "Routine");
await p.screenshot({ path: `${SP}/qa4-routine.png` });
await nav(p, "Home");
await p.screenshot({ path: `${SP}/qa4-home.png` });
console.log("errors:", JSON.stringify(errors.slice(0, 6)));
await b.close();
